'use client';

import { FormEvent, useEffect, useState } from 'react';

type Book = { id:string; title:string; author:string; genre?:string|null; synopsis?:string|null; coverUrl?:string|null; purchaseUrl?:string|null; epubKey?:string|null; epubName?:string|null; suggestedByLabel?:string|null; suggestedBy?:{id:string;name:string}; statuses?:{user:{name:string}}[]; isContested:boolean; contestedBy?:{name:string}|null; votes:{userId:string}[] };
type Message = { id:string; content:string; user:{name:string} };
type Member = {id:string; name:string; email:string; isAdmin:boolean};
type ReadingStatus = {userId:string; state:'FINISHED'|'READING'|'NOT_STARTED'; user:{id:string;name:string}};
type MonthlyReading = {id:string; month:string; startDate?:string|null; books:{book:Book}[]};
type Data = { club:{currentBook?:Book|null; nextMeetingAt?:string|null; meetingPlace?:string|null; meetingNotes?:string|null; pollOpen:boolean}; books:Book[]; messages:Message[]; members:Member[]; statuses:ReadingStatus[]; monthlyReadings:MonthlyReading[]; user:Member };
const nav = [{id:'home',icon:'⌂',label:'Início'},{id:'next',icon:'◌',label:'Votação'},{id:'books',icon:'▤',label:'Livros'},{id:'readings',icon:'▦',label:'Leituras'},{id:'profile',icon:'◉',label:'Perfil'}];
const emptyBook = {title:'',author:'',genre:'',synopsis:'',coverUrl:'',purchaseUrl:'',suggestedByLabel:''};

export default function ClubDashboard({userName,onSignOut}:{userName:string;onSignOut:()=>void}) {
  const [data,setData]=useState<Data|null>(null), [view,setView]=useState('home'), [notice,setNotice]=useState('');
  const [editing,setEditing]=useState<Book|null>(null), [details,setDetails]=useState<Book|null>(null), [adding,setAdding]=useState(false), [book,setBook]=useState(emptyBook), [adminEmail,setAdminEmail]=useState(''), [readingMonth,setReadingMonth]=useState(''), [readingBookIds,setReadingBookIds]=useState<string[]>([]), [meetingAt,setMeetingAt]=useState(''), [meetingPlace,setMeetingPlace]=useState(''), [meetingNotes,setMeetingNotes]=useState(''), [adminPanel,setAdminPanel]=useState<'reading'|'meeting'|'admins'|null>(null), [chosenVote,setChosenVote]=useState('');
  const load=async()=>{const r=await fetch('/api/club');setData(await r.json())};
  useEffect(()=>{void load()},[]);
  const add=async(e:FormEvent)=>{e.preventDefault();const r=await fetch('/api/books',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(book)});if(r.ok){setBook(emptyBook);setAdding(false);setNotice('Livro sugerido com sucesso.');void load()}else setNotice('Preencha título e autor.')};
  const vote=async(id:string)=>{const r=await fetch('/api/votes',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({bookId:id})});setNotice(r.ok?'Voto registrado.':'Livro indisponível para votação.');if(r.ok)void load()};
  const contest=async(id:string)=>{const r=await fetch(`/api/books/${id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({isContested:true})});setNotice(r.ok?'Livro contestado.':'Não foi possível contestar o livro.');if(r.ok)void load()};
  const saveEdit=async(e:FormEvent)=>{e.preventDefault();if(!editing)return;const {id,...body}=editing;const r=await fetch(`/api/books/${id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});if(r.ok){setEditing(null);setNotice('Informações atualizadas.');void load()}else setNotice('Não foi possível salvar agora.')};
  const addAdmin=async(e:FormEvent)=>{e.preventDefault();const r=await fetch('/api/admins',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:adminEmail})});const result=await r.json();if(r.ok){setAdminEmail('');setNotice(`${result.name} agora é administradora.`);void load()}else setNotice(result.error||'Não foi possível alterar a permissão.')};
  const saveMonthly=async(e:FormEvent)=>{e.preventDefault();const r=await fetch('/api/monthly-readings',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({month:readingMonth,bookIds:readingBookIds})});const result=await r.json();if(r.ok){setNotice('Leitura mensal definida.');setReadingBookIds([]);void load()}else setNotice(result.error||'Não foi possível salvar a leitura mensal.')};
  const saveMeeting=async(e:FormEvent)=>{e.preventDefault();const r=await fetch('/api/club',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({nextMeetingAt:meetingAt,meetingPlace,meetingNotes})});const result=await r.json();if(r.ok){setNotice('Próximo encontro atualizado.');void load()}else setNotice(result.error||'Não foi possível salvar o encontro.')};
  const uploadEpub=async(id:string,file?:File)=>{if(!file)return;if(!file.name.toLowerCase().endsWith('.epub')){setNotice('Selecione um arquivo EPUB.');return}setNotice('Enviando EPUB…');const prepared=await fetch(`/api/books/${id}/epub`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'prepare',name:file.name})});const data=await prepared.json();if(!prepared.ok){setNotice(data.error||'Não foi possível preparar o envio.');return}const upload=await fetch(data.url,{method:'PUT',headers:{'Content-Type':'application/epub+zip'},body:file});if(!upload.ok){setNotice('O envio ao armazenamento falhou.');return}const confirmed=await fetch(`/api/books/${id}/epub`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'confirm',key:data.key,name:file.name})});if(confirmed.ok){setNotice('EPUB enviado com sucesso.');void load()}else setNotice('O arquivo foi enviado, mas não pôde ser associado ao livro.')};
  const editReading=(reading:MonthlyReading)=>{setReadingMonth(reading.month.slice(0,7));setReadingBookIds(reading.books.map(({book})=>book.id));setAdminPanel('reading')};
  const deleteReading=async(id:string)=>{if(!confirm('Excluir esta leitura mensal?'))return;const r=await fetch(`/api/monthly-readings?id=${id}`,{method:'DELETE'});setNotice(r.ok?'Leitura excluída.':'Não foi possível excluir.');if(r.ok)void load()};
  const deleteBook=async(id:string)=>{if(!confirm('Excluir esta sugestão de livro?'))return;const r=await fetch(`/api/books/${id}`,{method:'DELETE'});setNotice(r.ok?'Sugestão excluída.':'Não foi possível excluir esta sugestão.');if(r.ok)void load()};
  const markRead=async(id:string)=>{const r=await fetch(`/api/books/${id}/read`,{method:'POST'});setNotice(r.ok?'Livro marcado como lido.':'Não foi possível registrar.');if(r.ok)void load()};
  const setPoll=async(open:boolean)=>{const r=await fetch('/api/club',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({pollOpen:open})});setNotice(r.ok?(open?'Enquete aberta.':'Enquete fechada.'):'Não foi possível alterar a enquete.');if(r.ok)void load()};
  const setReadingStatus=async(state:ReadingStatus['state'])=>{if(!data?.club.currentBook)return;const r=await fetch('/api/reading-status',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({bookId:data.club.currentBook.id,state})});setNotice(r.ok?'Status atualizado.':'Não foi possível atualizar o status.');if(r.ok)void load()};
  if(!data)return <main className="center">Carregando o clube…</main>;
  const current=data.club.currentBook, selectedBookIds=new Set(data.monthlyReadings.flatMap(reading=>reading.books.map(({book})=>book.id))), eligible=data.books.filter(b=>!b.isContested&&!selectedBookIds.has(b.id)), suggestedBooks=data.books.filter(b=>!selectedBookIds.has(b.id));
  const statusLabel={FINISHED:'Finalizado',READING:'Lendo',NOT_STARTED:'Não iniciado'} as const; const statusOrder={FINISHED:0,READING:1,NOT_STARTED:2}; const memberStatuses=data.members.map(member=>({member,state:data.statuses.find(status=>status.userId===member.id)?.state||'NOT_STARTED' as ReadingStatus['state']})).sort((a,b)=>statusOrder[a.state]-statusOrder[b.state]);
  return <main className="dashboard">
    <aside><div className="sidebar-brand"><img src="/logo-autentica-horizontal.png" alt="Autêntica Clube de Leitura"/></div><nav>{nav.map(item=><button className={view===item.id?'selected':''} onClick={()=>setView(item.id)} key={item.id} aria-label={item.label} title={item.label}><span>{item.icon}</span><em>{item.label}</em></button>)}</nav><button className="out" onClick={onSignOut}>Sair</button></aside>
    <section><div className="page-logo"><img src="/logo-autentica-horizontal.png" alt="Autêntica Clube de Leitura"/></div>{notice&&<p className="notice">{notice}</p>}
      {view==='home'&&<div className="home-view"><article className="current-reading"><div className="cover-slot">{current?.coverUrl?<img src={current.coverUrl} alt={`Capa de ${current.title}`}/>:<span>Leitura<br/>atual</span>}</div><div><p className="eyebrow">LEITURA DE {new Date().toLocaleDateString('pt-BR',{month:'long',year:'numeric'}).toUpperCase()}</p><h2>{current?.title||'Nenhuma leitura definida para este mês'}</h2><dl><div><dt>Autor</dt><dd>{current?.author||'—'}</dd></div><div><dt>Gênero</dt><dd>{current?.genre||'—'}</dd></div></dl></div></article><div className="cards"><article><p className="eyebrow">PRÓXIMO ENCONTRO</p><h3>{data.club.nextMeetingAt?new Date(data.club.nextMeetingAt).toLocaleDateString('pt-BR'):'A definir'}</h3><p>{data.club.meetingPlace||'O local será informado pelo clube.'}<br/>{data.club.meetingNotes||''}</p></article></div></div>}
      {view==='next'&&<><h2>Próxima votação</h2><p className="intro">{data.club.pollOpen?'Escolha apenas um livro para sua votação.':'A enquete está fechada.'}</p>{data.user.isAdmin&&<button onClick={()=>void setPoll(!data.club.pollOpen)}>{data.club.pollOpen?'Fechar enquete':'Abrir enquete'}</button>}{data.club.pollOpen&&<form className="poll-form" onSubmit={e=>{e.preventDefault();if(chosenVote)void vote(chosenVote)}}>{eligible.length?eligible.map(b=><label key={b.id}><input type="radio" name="vote" value={b.id} checked={chosenVote===b.id} onChange={()=>setChosenVote(b.id)}/><span>{b.title}<small>{b.author} · {b.votes.length} voto(s)</small></span></label>):<p className="empty">Ainda não há livros aptos.</p>}<button disabled={!chosenVote}>Confirmar voto</button></form>}</>}
      {view==='home'&&current&&<section className="reading-status"><p className="eyebrow">STATUS DE LEITURA</p><div className="status-actions"><button onClick={()=>void setReadingStatus('FINISHED')}>Finalizado</button><button onClick={()=>void setReadingStatus('READING')}>Lendo</button><button onClick={()=>void setReadingStatus('NOT_STARTED')}>Não iniciado</button></div><ul>{memberStatuses.map(({member,state})=><li key={member.id}><span>{member.name}</span><strong className={`status-${state}`}>{statusLabel[state]}</strong></li>)}</ul></section>}
      {view==='books'&&<><div className="section-heading books-heading"><div><p className="eyebrow">BIBLIOTECA DO CLUBE</p><h2>Livros Sugeridos</h2><p className="intro">Descubra as sugestões do clube e participe da escolha.</p></div><button className="add-book" onClick={()=>setAdding(true)} aria-label="Adicionar sugestão">+</button></div><div className="book-grid">{suggestedBooks.length?suggestedBooks.map(b=><BookCard key={b.id} book={b} isAdmin={data.user.isAdmin} onDetails={()=>setDetails(b)} onEdit={()=>setEditing(b)} onContest={()=>void contest(b.id)} onDelete={()=>void deleteBook(b.id)} onRead={()=>void markRead(b.id)} onUpload={file=>void uploadEpub(b.id,file)}/>):<p className="empty">Ainda não há sugestões. Use o botão + para adicionar o primeiro livro.</p>}</div></>}
      {view==='readings'&&<><div className="section-heading"><p className="eyebrow">CLUBE DE LEITURA</p><h2>Leituras</h2><p className="intro">Veja os livros escolhidos em cada mês.</p></div><ReadingCatalog readings={data.monthlyReadings} isAdmin={data.user.isAdmin} onEdit={editReading} onDelete={deleteReading}/></>}
      {view==='profile'&&<><h2>Meu perfil</h2><article className="profile-card"><div className="initial">{userName[0]}</div><div><h3>{userName}</h3><p>{data.user.isAdmin?'Você é administradora do clube.':'Seu perfil é conectado de forma segura ao clube.'}</p></div></article>{data.user.isAdmin&&<div className="admin-actions"><button onClick={()=>setAdminPanel('reading')}>Definir leitura do mês</button><button onClick={()=>setAdminPanel('meeting')}>Configurar próximo encontro</button><button onClick={()=>setAdminPanel('admins')}>Gerenciar administradoras</button></div>}</>}
      {view==='readings'&&current&&<section className="reading-status"><p className="eyebrow">ACOMPANHAMENTO DA LEITURA ATUAL</p><ul>{memberStatuses.map(({member,state})=><li key={member.id}><span>{member.name}</span><strong className={`status-${state}`}>{statusLabel[state]}</strong></li>)}</ul></section>}
    </section>
    {adding&&<BookForm title="Adicionar sugestão" book={book} setBook={setBook} onSubmit={add} onClose={()=>{setAdding(false);setBook(emptyBook)}} isAdmin={data.user.isAdmin}/>}
    {editing&&<EditForm book={editing} setBook={setEditing} onSubmit={saveEdit} onClose={()=>setEditing(null)}/>}
    {details&&<div className="edit-layer" role="dialog" aria-modal="true" aria-label="Informações do livro"><article className="edit-panel book-details"><button className="dialog-close" onClick={()=>setDetails(null)} aria-label="Fechar">×</button><p className="eyebrow">SOBRE O LIVRO</p><h2>{details.title}</h2><p className="book-author">{details.author}</p><p className="book-genre">{details.genre||'Gênero não informado'}</p><p className="details-synopsis">{details.synopsis||'A sinopse deste livro ainda não foi informada.'}</p>{details.purchaseUrl&&<a className="details-buy" href={details.purchaseUrl} target="_blank" rel="noreferrer">Ir para compra</a>}</article></div>}
    {adminPanel==='reading'&&<div className="edit-layer" role="dialog" aria-modal="true"><form className="edit-panel monthly-form" onSubmit={async e=>{await saveMonthly(e);setAdminPanel(null)}}><button type="button" className="dialog-close" onClick={()=>setAdminPanel(null)} aria-label="Fechar">×</button><p className="eyebrow">ADMINISTRAÇÃO</p><h2>Definir leitura do mês</h2><label>Mês da leitura<input required type="month" value={readingMonth} onChange={e=>setReadingMonth(e.target.value)}/></label><fieldset><legend>Livros oficiais</legend>{eligible.map(book=><label className="book-choice" key={book.id}><input type="checkbox" checked={readingBookIds.includes(book.id)} onChange={e=>setReadingBookIds(e.target.checked?[...readingBookIds,book.id]:readingBookIds.filter(id=>id!==book.id))}/><span><strong>{book.title}</strong><small>{book.author}</small></span></label>)}</fieldset><div className="edit-actions"><button type="button" onClick={()=>setAdminPanel(null)}>Cancelar</button><button>Salvar leitura</button></div></form></div>}
    {adminPanel==='meeting'&&<div className="edit-layer" role="dialog" aria-modal="true"><form className="edit-panel monthly-form meeting-form" onSubmit={async e=>{await saveMeeting(e);setAdminPanel(null)}}><button type="button" className="dialog-close" onClick={()=>setAdminPanel(null)} aria-label="Fechar">×</button><p className="eyebrow">PRÓXIMO ENCONTRO</p><h2>Dados do encontro</h2><label>Data e horário<input required type="datetime-local" value={meetingAt} onChange={e=>setMeetingAt(e.target.value)}/></label><label>Local<input value={meetingPlace} onChange={e=>setMeetingPlace(e.target.value)} placeholder="Ex.: Livraria, café ou chamada online"/></label><label>Observações<textarea value={meetingNotes} onChange={e=>setMeetingNotes(e.target.value)} placeholder="Ex.: levar uma frase favorita"/></label><div className="edit-actions"><button type="button" onClick={()=>setAdminPanel(null)}>Cancelar</button><button>Salvar encontro</button></div></form></div>}
    {adminPanel==='admins'&&<div className="edit-layer" role="dialog" aria-modal="true"><article className="edit-panel admin-card"><button className="dialog-close" onClick={()=>setAdminPanel(null)} aria-label="Fechar">×</button><p className="eyebrow">ADMINISTRAÇÃO</p><h2>Administradoras</h2><ul>{data.members.filter(member=>member.isAdmin).map(member=><li key={member.id}><strong>{member.name}</strong><span>{member.email}</span></li>)}</ul><form onSubmit={async e=>{await addAdmin(e);setAdminPanel(null)}}><label>Adicionar administradora<input required type="email" placeholder="E-mail de uma participante" value={adminEmail} onChange={e=>setAdminEmail(e.target.value)}/></label><button>Conceder acesso</button></form></article></div>}
  </main>
}

function BookForm({title,book,setBook,onSubmit,onClose,isAdmin}:{title:string;book:typeof emptyBook;setBook:(book:typeof emptyBook)=>void;onSubmit:(e:FormEvent)=>void;onClose:()=>void;isAdmin:boolean}) { return <div className="edit-layer" role="dialog" aria-modal="true"><form className="edit-panel" onSubmit={onSubmit}><button type="button" className="dialog-close" onClick={onClose} aria-label="Fechar">×</button><p className="eyebrow">LIVRO SUGERIDO</p><h2>{title}</h2><label>Título<input required value={book.title} onChange={e=>setBook({...book,title:e.target.value})}/></label><label>Autor(a)<input required value={book.author} onChange={e=>setBook({...book,author:e.target.value})}/></label>{isAdmin&&<label>Sugerido por<input value={book.suggestedByLabel} onChange={e=>setBook({...book,suggestedByLabel:e.target.value})}/></label>}<label>Gênero<input value={book.genre} onChange={e=>setBook({...book,genre:e.target.value})}/></label><label>URL da capa<input type="url" value={book.coverUrl} onChange={e=>setBook({...book,coverUrl:e.target.value})}/></label><label>Link de compra<input type="url" value={book.purchaseUrl} onChange={e=>setBook({...book,purchaseUrl:e.target.value})}/></label><label>Sinopse<textarea value={book.synopsis} onChange={e=>setBook({...book,synopsis:e.target.value})}/></label><div className="edit-actions"><button type="button" onClick={onClose}>Cancelar</button><button>Salvar sugestão</button></div></form></div> }

function EditForm({book,setBook,onSubmit,onClose}:{book:Book;setBook:(book:Book)=>void;onSubmit:(e:FormEvent)=>void;onClose:()=>void}) { return <div className="edit-layer" role="dialog" aria-modal="true"><form className="edit-panel" onSubmit={onSubmit}><button type="button" className="dialog-close" onClick={onClose} aria-label="Fechar">×</button><p className="eyebrow">EDITAR SUGESTÃO</p><h2>{book.title}</h2><p className="locked">O título permanece protegido.</p><label>Autor(a)<input value={book.author} onChange={e=>setBook({...book,author:e.target.value})}/></label><label>Gênero<input value={book.genre||''} onChange={e=>setBook({...book,genre:e.target.value})}/></label><label>URL da capa<input value={book.coverUrl||''} onChange={e=>setBook({...book,coverUrl:e.target.value})}/></label><label>Link de compra<input value={book.purchaseUrl||''} onChange={e=>setBook({...book,purchaseUrl:e.target.value})}/></label><label>Sinopse<textarea value={book.synopsis||''} onChange={e=>setBook({...book,synopsis:e.target.value})}/></label><div className="edit-actions"><button type="button" onClick={onClose}>Cancelar</button><button>Salvar alterações</button></div></form></div> }

function ReadingCatalog({readings,isAdmin,onEdit,onDelete}:{readings:MonthlyReading[];isAdmin:boolean;onEdit:(reading:MonthlyReading)=>void;onDelete:(id:string)=>void}) { return <div className="reading-catalog">{readings.length?readings.flatMap(reading=>reading.books.map(({book})=><article key={`${reading.id}-${book.id}`}><div className="catalog-cover">{book.coverUrl?<img src={book.coverUrl} alt={`Capa de ${book.title}`}/>:<span>Sem capa</span>}</div><p>{new Date(reading.month).toLocaleDateString('pt-BR',{month:'long',year:'numeric'})}</p>{isAdmin&&<div><button onClick={()=>onEdit(reading)}>Editar</button><button onClick={()=>onDelete(reading.id)}>Excluir</button></div>}</article>)):<p className="empty">Nenhuma leitura mensal definida ainda.</p>}</div> }

function BookCard({book,isAdmin,onDetails,onEdit,onContest,onDelete,onRead,onUpload}:{book:Book;isAdmin:boolean;onDetails:()=>void;onEdit:()=>void;onContest:()=>void;onDelete:()=>void;onRead:()=>void;onUpload:(file?:File)=>void}) { const [open,setOpen]=useState(false); return <article className={`book-card ${book.isContested?'contested':''}`}><div className="book-cover">{book.coverUrl?<img src={book.coverUrl} alt={`Capa de ${book.title}`}/>:<span>Sem<br/>capa</span>}</div><div className="book-info"><p className="book-genre">{book.genre||'Gênero não informado'}</p><h3>{book.title}</h3><p className="book-author">{book.author}</p><p className="book-suggester">Sugerido por {book.suggestedByLabel||book.suggestedBy?.name||'participante do clube'}</p>{book.statuses?.length?<p className="book-suggester">Já lido por {book.statuses.map(s=>s.user.name).join(', ')}</p>:null}{book.isContested&&<p className="contested-label">Livro contestado{book.contestedBy?.name?` por ${book.contestedBy.name}`:''}.</p>}<div className="book-actions"><button className="add-book card-menu" onClick={()=>setOpen(!open)} aria-label="Ações do livro">+</button>{open&&<div className="book-menu"><button onClick={onDetails}>Mais informações</button><button onClick={onRead}>Já li</button><button onClick={onEdit}>Editar</button>{!book.isContested&&<button className="danger" onClick={onContest}>Contestar</button>}<button className="danger" onClick={onDelete}>Excluir</button>{book.purchaseUrl&&<a href={book.purchaseUrl} target="_blank" rel="noreferrer">Comprar</a>}{book.epubKey&&<a href={`/api/books/${book.id}/epub`}>Baixar EPUB</a>}{isAdmin&&<label className="epub-upload">Enviar EPUB<input type="file" accept=".epub,application/epub+zip" onChange={e=>onUpload(e.target.files?.[0])}/></label>}</div>}</div></div></article> }
