'use client';

import { FormEvent, useEffect, useState } from 'react';

type Book = { id:string; title:string; author:string; genre?:string|null; synopsis?:string|null; coverUrl?:string|null; purchaseUrl?:string|null; epubKey?:string|null; epubName?:string|null; suggestedByLabel?:string|null; suggestedBy?:{id:string;name:string}; statuses?:{user:{name:string}}[]; ratings:{userId:string;score:number}[]; isContested:boolean; contestedBy?:{name:string}|null; votes:{userId:string}[] };
type Message = { id:string; content:string; createdAt:string; user:{id:string;name:string;imageUrl?:string|null} };
type Member = {id:string; name:string; email:string; imageUrl?:string|null; isAdmin:boolean};
type ReadingStatus = {userId:string; bookId?:string; state:'FINISHED'|'READING'|'NOT_STARTED'|'ABANDONED'; user:{id:string;name:string}};
type MonthlyReading = {id:string; month:string; startDate?:string|null; books:{book:Book}[]};
type Report = {members:{id:string;name:string;email:string;finished:number;abandoned:number}[];books:{id:string;title:string;readers:string[]}[]};
type Comment = {id:string;content:string;createdAt:string;user:{id:string;name:string;imageUrl?:string|null};book:{id:string;title:string}};
type ReadingActivity = {id:string;state:ReadingStatus['state'];createdAt:string;user:{id:string;name:string;imageUrl?:string|null};book:{id:string;title:string}};
type Data = { club:{currentBook?:Book|null; nextMeetingAt?:string|null; meetingPlace?:string|null; meetingNotes?:string|null; pollOpen:boolean}; books:Book[]; messages:Message[]; comments:Comment[]; activities:ReadingActivity[]; members:Member[]; statuses:ReadingStatus[]; allStatuses:ReadingStatus[]; ownStatuses:{bookId:string;state:ReadingStatus['state']}[]; ownRatings:{bookId:string;score:number}[]; monthlyReadings:MonthlyReading[]; user:Member; profileStats:{finished:number;abandoned:number}; readerRanking:{id:string;name:string;count:number}[]; bookRanking:{id:string;title:string;count:number}[]; ratingRanking:{id:string;title:string;coverUrl?:string|null;average:number;count:number}[]; readingReport:Report|null };
const nav = [{id:'home',icon:'⌂',label:'Início'},{id:'next',icon:'◌',label:'Votação'},{id:'books',icon:'▤',label:'Livros'},{id:'readings',icon:'▦',label:'Leituras'},{id:'feed',icon:'◍',label:'Feed'},{id:'profile',icon:'◉',label:'Perfil'}];
const emptyBook = {title:'',author:'',genre:'',synopsis:'',coverUrl:'',purchaseUrl:'',suggestedByLabel:''};

export default function ClubDashboard({userName,onSignOut}:{userName:string;onSignOut:()=>void}) {
  const [data,setData]=useState<Data|null>(null), [view,setView]=useState('home'), [notice,setNotice]=useState('');
  const [editing,setEditing]=useState<Book|null>(null), [details,setDetails]=useState<Book|null>(null), [commentBook,setCommentBook]=useState<Book|null>(null), [publicProfile,setPublicProfile]=useState<Member|null>(null), [adding,setAdding]=useState(false), [book,setBook]=useState(emptyBook), [adminEmail,setAdminEmail]=useState(''), [readingMonth,setReadingMonth]=useState(''), [readingBookIds,setReadingBookIds]=useState<string[]>([]), [meetingAt,setMeetingAt]=useState(''), [meetingPlace,setMeetingPlace]=useState(''), [meetingNotes,setMeetingNotes]=useState(''), [adminPanel,setAdminPanel]=useState<'reading'|'meeting'|'admins'|'report'|null>(null), [chosenVote,setChosenVote]=useState(''), [editingProfile,setEditingProfile]=useState(false), [profileName,setProfileName]=useState(''), [profileFile,setProfileFile]=useState<File|null>(null), [commentContent,setCommentContent]=useState(''), [groupMessage,setGroupMessage]=useState('');
  const load=async()=>{const r=await fetch('/api/club');setData(await r.json())};
  useEffect(()=>{void load()},[]);
  const add=async(e:FormEvent)=>{e.preventDefault();const r=await fetch('/api/books',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(book)});if(r.ok){setBook(emptyBook);setAdding(false);setNotice('Livro sugerido com sucesso.');void load()}else setNotice('Preencha título e autor.')};
  const vote=async(id:string)=>{const r=await fetch('/api/votes',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({bookId:id})});setNotice(r.ok?'Voto registrado.':'Livro indisponível para votação.');if(r.ok)void load()};
  const contest=async(id:string)=>{const r=await fetch(`/api/books/${id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({isContested:true})});setNotice(r.ok?'Livro contestado.':'Não foi possível contestar o livro.');if(r.ok)void load()};
  const saveEdit=async(e:FormEvent)=>{e.preventDefault();if(!editing)return;const {id,...body}=editing;const r=await fetch(`/api/books/${id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});if(r.ok){setEditing(null);setNotice('Informações atualizadas.');void load()}else setNotice('Não foi possível salvar agora.')};
  const addAdmin=async(e:FormEvent)=>{e.preventDefault();const r=await fetch('/api/admins',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:adminEmail})});const result=await r.json();if(r.ok){setAdminEmail('');setNotice(`${result.name} agora é administradora.`);void load()}else setNotice(result.error||'Não foi possível alterar a permissão.')};
  const saveMonthly=async(e:FormEvent)=>{e.preventDefault();const r=await fetch('/api/monthly-readings',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({month:readingMonth,bookIds:readingBookIds})});const result=await r.json();if(r.ok){setNotice('Leitura mensal definida.');setReadingBookIds([]);void load()}else setNotice(result.error||'Não foi possível salvar a leitura mensal.')};
  const saveMeeting=async(e:FormEvent)=>{e.preventDefault();const r=await fetch('/api/club',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({nextMeetingAt:meetingAt,meetingPlace,meetingNotes})});const result=await r.json();if(r.ok){setNotice('Próximo encontro atualizado.');void load()}else setNotice(result.error||'Não foi possível salvar o encontro.')};
  const uploadEpub=async(id:string,file?:File)=>{if(!file)return;if(!file.name.toLowerCase().endsWith('.epub')){setNotice('Selecione um arquivo EPUB.');return}setNotice('Enviando EPUB…');const prepared=await fetch(`/api/books/${id}/epub`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'prepare',name:file.name})});const data=await prepared.json();if(!prepared.ok){setNotice(data.error||'Não foi possível preparar o envio.');return}const upload=await fetch(data.url,{method:'PUT',headers:{'Content-Type':'application/epub+zip'},body:file});if(!upload.ok){setNotice('O envio ao armazenamento falhou.');return}const confirmed=await fetch(`/api/books/${id}/epub`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'confirm',key:data.key,name:file.name})});if(confirmed.ok){setNotice('EPUB enviado com sucesso.');void load()}else setNotice('O arquivo foi enviado, mas não pôde ser associado ao livro.')};
  const editReading=(reading:MonthlyReading)=>{setReadingMonth(reading.month.slice(0,7));setReadingBookIds(reading.books.map(({book})=>book.id));setAdminPanel('reading')};
  const deleteReading=async(id:string)=>{if(!confirm('Excluir esta leitura mensal?'))return;const r=await fetch(`/api/monthly-readings?id=${id}`,{method:'DELETE'});setNotice(r.ok?'Leitura excluída.':'Não foi possível excluir.');if(r.ok)void load()};
  const deleteBook=async(id:string)=>{if(!confirm('Excluir esta sugestão de livro?'))return;const r=await fetch(`/api/books/${id}`,{method:'DELETE'});setNotice(r.ok?'Sugestão excluída.':'Não foi possível excluir esta sugestão.');if(r.ok)void load()};
  const markRead=async(id:string)=>{const r=await fetch(`/api/books/${id}/read`,{method:'POST'});setNotice(r.ok?'Livro marcado como lido.':'Não foi possível registrar.');if(r.ok)void load()};
  const setBookStatus=async(bookId:string,state:ReadingStatus['state'])=>{const r=await fetch('/api/reading-status',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({bookId,state})});setNotice(r.ok?'Status de leitura atualizado.':'Não foi possível atualizar o status.');if(r.ok)void load()};
  const setPoll=async(open:boolean)=>{const r=await fetch('/api/club',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({pollOpen:open})});setNotice(r.ok?(open?'Enquete aberta.':'Enquete fechada.'):'Não foi possível alterar a enquete.');if(r.ok)void load()};
  const setReadingStatus=async(state:ReadingStatus['state'])=>{if(!data?.club.currentBook)return;const r=await fetch('/api/reading-status',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({bookId:data.club.currentBook.id,state})});setNotice(r.ok?'Status atualizado.':'Não foi possível atualizar o status.');if(r.ok)void load()};
  const addComment=async(e:FormEvent)=>{e.preventDefault();if(!commentBook)return;const r=await fetch('/api/comments',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({bookId:commentBook.id,content:commentContent})});const result=await r.json();if(r.ok){setCommentContent('');setNotice('Comentário publicado.');void load()}else setNotice(result.error||'Não foi possível publicar o comentário.')};
  const updateComment=async(id:string,content:string)=>{const r=await fetch(`/api/comments/${id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({content})});const result=await r.json();setNotice(r.ok?'Comentário atualizado.':result.error||'Não foi possível atualizar o comentário.');if(r.ok)void load();return r.ok};
  const deleteComment=async(id:string)=>{if(!confirm('Excluir este comentário?'))return false;const r=await fetch(`/api/comments/${id}`,{method:'DELETE'});const result=await r.json();setNotice(r.ok?'Comentário excluído.':result.error||'Não foi possível excluir o comentário.');if(r.ok)void load();return r.ok};
  const rateBook=async(bookId:string,score:number)=>{const r=await fetch('/api/ratings',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({bookId,score})});const result=await r.json();setNotice(r.ok?'Avaliação registrada.':result.error||'Não foi possível registrar a avaliação.');if(r.ok)void load()};
  const sendGroupMessage=async(e:FormEvent)=>{e.preventDefault();const r=await fetch('/api/messages',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({content:groupMessage})});const result=await r.json();if(r.ok){setGroupMessage('');void load()}else setNotice(result.error||'Não foi possível enviar a mensagem.')};
  const uploadProfilePhoto=async(file:File)=>{if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>5*1024*1024){setNotice('Escolha uma imagem JPG, PNG ou WEBP de até 5 MB.');return false}const prepared=await fetch('/api/profile/photo',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'prepare',type:file.type})});const data=await prepared.json();if(!prepared.ok){setNotice(data.error||'Não foi possível preparar a foto.');return false}const upload=await fetch(data.url,{method:'PUT',headers:{'Content-Type':file.type},body:file});if(!upload.ok){setNotice('O envio da foto falhou.');return false}const confirmed=await fetch('/api/profile/photo',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'confirm',key:data.key})});if(!confirmed.ok){setNotice('A foto foi enviada, mas não pôde ser associada ao perfil.');return false}return true};
  const saveProfile=async(e:FormEvent)=>{e.preventDefault();const r=await fetch('/api/profile',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:profileName})});const result=await r.json();if(!r.ok){setNotice(result.error||'Não foi possível atualizar o perfil.');return}if(profileFile&&!(await uploadProfilePhoto(profileFile)))return;setProfileFile(null);setEditingProfile(false);setNotice('Perfil atualizado.');void load()};
  if(!data)return <main className="center">Carregando o clube…</main>;
  const current=data.club.currentBook, selectedBookIds=new Set(data.monthlyReadings.flatMap(reading=>reading.books.map(({book})=>book.id))), eligible=data.books.filter(b=>!b.isContested&&!selectedBookIds.has(b.id)), suggestedBooks=data.books.filter(b=>!selectedBookIds.has(b.id));
  const statusLabel={FINISHED:'Finalizado',READING:'Lendo',NOT_STARTED:'Não iniciado',ABANDONED:'Abandonado'} as const; const statusOrder={FINISHED:0,READING:1,NOT_STARTED:2,ABANDONED:3}; const memberStatuses=data.members.map(member=>({member,state:data.statuses.find(status=>status.userId===member.id)?.state||'NOT_STARTED' as ReadingStatus['state']})).sort((a,b)=>statusOrder[a.state]-statusOrder[b.state]); const readingNow=memberStatuses.filter(({state})=>state==='READING').length, finishedNow=memberStatuses.filter(({state})=>state==='FINISHED').length, totalMembers=data.members.length; const currentComments=current?data.comments.filter(comment=>comment.book.id===current.id):[]; const feedItems=[...data.messages.map(message=>({kind:'message' as const,createdAt:message.createdAt,message})),...data.activities.filter(activity=>activity.state!=='NOT_STARTED').map(activity=>({kind:'status' as const,createdAt:activity.createdAt,activity}))].sort((a,b)=>new Date(a.createdAt).getTime()-new Date(b.createdAt).getTime());
  return <main className="dashboard">
    <aside><div className="sidebar-brand"><img src="/logo-autentica-horizontal.png" alt="Autêntica Clube de Leitura"/></div><nav>{nav.map(item=><button className={view===item.id?'selected':''} onClick={()=>setView(item.id)} key={item.id} aria-label={item.label} title={item.label}><span>{item.icon}</span><em>{item.label}</em></button>)}</nav><button className="out" onClick={onSignOut}>Sair</button></aside>
    <section><div className="page-logo"><img src="/logo-autentica-horizontal.png" alt="Autêntica Clube de Leitura"/></div>{notice&&<p className="notice">{notice}</p>}
      {view==='home'&&<div className="home-view"><article className="current-reading featured-reading"><div className="cover-slot">{current?.coverUrl?<img src={current.coverUrl} alt={`Capa de ${current.title}`}/>:<span>Leitura<br/>atual</span>}</div><div><p className="eyebrow">EM LEITURA · {new Date().toLocaleDateString('pt-BR',{month:'long',year:'numeric'}).toUpperCase()}</p><h2>{current?.title||'Nenhuma leitura definida para este mês'}</h2><dl><div><dt>Autor</dt><dd>{current?.author||'—'}</dd></div><div><dt>Gênero</dt><dd>{current?.genre||'—'}</dd></div></dl>{current&&<button className="book-comment-link" onClick={()=>setCommentBook(current)}>Comentários</button>}</div></article>{current&&<article className="reading-scoreboard"><div><p className="eyebrow">TERMÔMETRO DA LEITURA</p><h3>Como o clube está avançando</h3></div><div className="scoreboard-stats"><div><strong>{readingNow}</strong><span>lendo agora</span></div><div><strong>{finishedNow}</strong><span>finalizaram</span></div><div><strong>{totalMembers}</strong><span>participantes</span></div></div></article>}<div className="cards"><article><p className="eyebrow">PRÓXIMO ENCONTRO</p><h3>{data.club.nextMeetingAt?new Date(data.club.nextMeetingAt).toLocaleDateString('pt-BR'):'A definir'}</h3><p>{data.club.meetingPlace||'O local será informado pelo clube.'}<br/>{data.club.meetingNotes||''}</p></article></div>{current&&<article className="current-comments-panel"><header><div><p className="eyebrow">CONVERSA SOBRE A LEITURA ATUAL</p><h3>Comentários do clube</h3></div><button onClick={()=>setCommentBook(current)}>Adicionar comentário</button></header>{currentComments.length?<CommentList comments={currentComments.slice(0,3)} currentUserId={data.user.id} onUpdate={updateComment} onDelete={deleteComment}/>:<p className="empty-comments">Ainda não há comentários. Compartilhe uma impressão sobre a leitura.</p>}{currentComments.length>3&&<button className="show-comments" onClick={()=>setCommentBook(current)}>Ver todos os comentários</button>}</article>}</div>}
      {view==='next'&&<><h2>Próxima votação</h2><p className="intro">{data.club.pollOpen?'Escolha apenas um livro para sua votação.':'A enquete está fechada.'}</p>{data.user.isAdmin&&<button onClick={()=>void setPoll(!data.club.pollOpen)}>{data.club.pollOpen?'Fechar enquete':'Abrir enquete'}</button>}{data.club.pollOpen&&<form className="poll-form" onSubmit={e=>{e.preventDefault();if(chosenVote)void vote(chosenVote)}}>{eligible.length?eligible.map(b=><label key={b.id}><input type="radio" name="vote" value={b.id} checked={chosenVote===b.id} onChange={()=>setChosenVote(b.id)}/><span>{b.title}<small>{b.author} · {b.votes.length} voto(s)</small></span></label>):<p className="empty">Ainda não há livros aptos.</p>}<button disabled={!chosenVote}>Confirmar voto</button></form>}</>}
      {view==='home'&&current&&<section className="reading-status"><p className="eyebrow">STATUS DE LEITURA</p><div className="status-actions"><button onClick={()=>void setReadingStatus('FINISHED')}>Finalizado</button><button onClick={()=>void setReadingStatus('READING')}>Lendo</button><button onClick={()=>void setReadingStatus('NOT_STARTED')}>Não iniciado</button></div><ul>{memberStatuses.map(({member,state})=><li key={member.id}><button className="member-link" onClick={()=>setPublicProfile(member)}>{member.name}</button><strong className={`status-${state}`}>{statusLabel[state]}</strong></li>)}</ul></section>}
      {view==='home'&&<article className="book-ranking"><p className="eyebrow">RANKING DE LEITURA</p>{data.readerRanking.length?<ol>{data.readerRanking.map((item,index)=>{const member=data.members.find(member=>member.id===item.id);return <li key={item.id}><button className="member-link ranking-member" onClick={()=>member&&setPublicProfile(member)}>{index+1}. {item.name}</button><strong>{item.count} {item.count===1?'livro lido':'livros lidos'}</strong></li>})}</ol>:<p className="ranking-empty">As participantes aparecerão aqui quando entrarem no clube.</p>}</article>}
      {view==='home'&&<article className="rating-ranking"><p className="eyebrow">MELHORES AVALIAÇÕES</p><h3>Livros favoritos do clube</h3>{data.ratingRanking.length?<ol>{data.ratingRanking.slice(0,5).map((book,index)=><li key={book.id}><span>{index+1}. {book.title}</span><strong>★ {book.average.toFixed(1)} <small>({book.count})</small></strong></li>)}</ol>:<p className="ranking-empty">As avaliações aparecerão aqui quando as participantes derem estrelas às leituras.</p>}</article>}
      {view==='books'&&<><div className="section-heading books-heading"><div><p className="eyebrow">BIBLIOTECA DO CLUBE</p><h2>Livros Sugeridos</h2><p className="intro">Descubra as sugestões do clube e participe da escolha.</p></div><button className="add-book" onClick={()=>setAdding(true)} aria-label="Adicionar sugestão">+</button></div><div className="book-grid">{suggestedBooks.length?suggestedBooks.map(b=><BookCard key={b.id} book={b} isAdmin={data.user.isAdmin} onDetails={()=>setDetails(b)} onComments={()=>setCommentBook(b)} onEdit={()=>setEditing(b)} onContest={()=>void contest(b.id)} onDelete={()=>void deleteBook(b.id)} onRead={()=>void markRead(b.id)} onUpload={file=>void uploadEpub(b.id,file)}/>):<p className="empty">Ainda não há sugestões. Use o botão + para adicionar o primeiro livro.</p>}</div></>}
      {view==='readings'&&<><div className="section-heading"><p className="eyebrow">CLUBE DE LEITURA</p><h2>Leituras</h2><p className="intro">Registre o status e a sua avaliação de cada livro que fez parte do clube.</p></div><ReadingCatalog readings={data.monthlyReadings} ownStatuses={data.ownStatuses} ownRatings={data.ownRatings} isAdmin={data.user.isAdmin} onEdit={editReading} onDelete={deleteReading} onStatus={setBookStatus} onComments={setCommentBook} onRate={rateBook}/></>}
      {view==='feed'&&<><div className="section-heading"><p className="eyebrow">CONVERSA DO CLUBE</p><h2>Grupo Leitura Autêntica</h2><p className="intro">Troque recados e impressões com as participantes.</p></div><div className="group-chat">{feedItems.length?<div className="group-messages">{feedItems.map(item=>item.kind==='message'?<article className={`group-message ${item.message.user.id===data.user.id?'own-message':''}`} key={`message-${item.message.id}`}><CommentHeader user={item.message.user} date={item.message.createdAt}/><p>{item.message.content}</p></article>:<article className="group-status" key={`activity-${item.activity.id}`}><span>●</span>{item.activity.state==='FINISHED'?`${item.activity.user.name} finalizou a leitura de ${item.activity.book.title}.`:item.activity.state==='READING'?`${item.activity.user.name} começou a leitura de ${item.activity.book.title}.`:`${item.activity.user.name} abandonou a leitura de ${item.activity.book.title}.`}</article>)}</div>:<p className="empty">Ainda não há mensagens. Inicie a conversa do clube.</p>}<form className="group-composer" onSubmit={sendGroupMessage}><textarea required maxLength={500} value={groupMessage} onChange={e=>setGroupMessage(e.target.value)} placeholder="Escreva uma mensagem para o grupo…"/><div><small>{groupMessage.length}/500</small><button aria-label="Enviar mensagem">Enviar</button></div></form></div></>}
      {view==='profile'&&<><article className="profile-card"><div className="initial">{data.user.imageUrl?<img src={data.user.imageUrl.startsWith('r2:')?'/api/profile/photo':data.user.imageUrl} alt={`Foto de ${data.user.name}`}/>:data.user.name[0]}</div><div><h3>{data.user.name}</h3><p>{data.user.email}</p><p>{data.user.isAdmin?'Você é administradora do clube.':'Seu perfil é conectado de forma segura ao clube.'}</p></div><button className="profile-edit" onClick={()=>{setProfileName(data.user.name);setProfileFile(null);setEditingProfile(true)}}>Editar perfil</button></article><div className="profile-stats"><article><strong>{data.profileStats.finished}</strong><span>Livros lidos</span></article><article><strong>{data.profileStats.abandoned}</strong><span>Livros abandonados</span></article></div>{data.user.isAdmin&&<div className="admin-actions"><button onClick={()=>setAdminPanel('reading')}>Definir leitura do mês</button><button onClick={()=>setAdminPanel('meeting')}>Configurar próximo encontro</button><button onClick={()=>setAdminPanel('admins')}>Gerenciar administradoras</button><button onClick={()=>setAdminPanel('report')}>Gerar relatório de leitura</button></div>}</>}
    </section>
    {adding&&<BookForm title="Adicionar sugestão" book={book} setBook={setBook} onSubmit={add} onClose={()=>{setAdding(false);setBook(emptyBook)}} isAdmin={data.user.isAdmin}/>}
    {editing&&<EditForm book={editing} setBook={setEditing} onSubmit={saveEdit} onClose={()=>setEditing(null)}/>}
    {details&&<div className="edit-layer" role="dialog" aria-modal="true" aria-label="Informações do livro"><article className="edit-panel book-details"><button className="dialog-close" onClick={()=>setDetails(null)} aria-label="Fechar">×</button><p className="eyebrow">SOBRE O LIVRO</p><h2>{details.title}</h2><p className="book-author">{details.author}</p><p className="book-genre">{details.genre||'Gênero não informado'}</p><p className="details-synopsis">{details.synopsis||'A sinopse deste livro ainda não foi informada.'}</p>{details.purchaseUrl&&<a className="details-buy" href={details.purchaseUrl} target="_blank" rel="noreferrer">Ir para compra</a>}</article></div>}
    {commentBook&&<div className="edit-layer" role="dialog" aria-modal="true" aria-label="Comentários do livro"><article className="edit-panel comments-dialog"><button className="dialog-close" onClick={()=>{setCommentBook(null);setCommentContent('')}} aria-label="Fechar">×</button><p className="eyebrow">CONVERSA DO CLUBE</p><h2>{commentBook.title}</h2><CommentList comments={data.comments.filter(comment=>comment.book.id===commentBook.id)} currentUserId={data.user.id} onUpdate={updateComment} onDelete={deleteComment}/><form className="comment-composer" onSubmit={addComment}><label>Adicionar comentário<textarea required maxLength={300} value={commentContent} onChange={e=>setCommentContent(e.target.value)} placeholder="Escreva a sua impressão sobre a leitura…"/></label><div><small>{commentContent.length}/300</small><button>Publicar comentário</button></div></form></article></div>}
    {publicProfile&&<PublicProfile member={publicProfile} books={data.books.filter(book=>data.allStatuses.some(status=>status.userId===publicProfile.id&&status.bookId===book.id&&status.state==='FINISHED'))} onClose={()=>setPublicProfile(null)}/>}
    {editingProfile&&<div className="edit-layer" role="dialog" aria-modal="true" aria-label="Editar perfil"><form className="edit-panel" onSubmit={saveProfile}><button type="button" className="dialog-close" onClick={()=>setEditingProfile(false)} aria-label="Fechar">×</button><p className="eyebrow">SEU PERFIL</p><h2>Editar perfil</h2><label>Nome<input required value={profileName} onChange={e=>setProfileName(e.target.value)}/></label><label>Foto de perfil<input type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>setProfileFile(e.target.files?.[0]||null)}/><small>JPG, PNG ou WEBP, até 5 MB{profileFile?` · ${profileFile.name}`:''}</small></label><div className="edit-actions"><button type="button" onClick={()=>setEditingProfile(false)}>Cancelar</button><button>Salvar perfil</button></div></form></div>}
    {adminPanel==='reading'&&<div className="edit-layer" role="dialog" aria-modal="true"><form className="edit-panel monthly-form" onSubmit={async e=>{await saveMonthly(e);setAdminPanel(null)}}><button type="button" className="dialog-close" onClick={()=>setAdminPanel(null)} aria-label="Fechar">×</button><p className="eyebrow">ADMINISTRAÇÃO</p><h2>Definir leitura do mês</h2><label>Mês da leitura<input required type="month" value={readingMonth} onChange={e=>setReadingMonth(e.target.value)}/></label><fieldset><legend>Livros oficiais</legend>{eligible.map(book=><label className="book-choice" key={book.id}><input type="checkbox" checked={readingBookIds.includes(book.id)} onChange={e=>setReadingBookIds(e.target.checked?[...readingBookIds,book.id]:readingBookIds.filter(id=>id!==book.id))}/><span><strong>{book.title}</strong><small>{book.author}</small></span></label>)}</fieldset><div className="edit-actions"><button type="button" onClick={()=>setAdminPanel(null)}>Cancelar</button><button>Salvar leitura</button></div></form></div>}
    {adminPanel==='meeting'&&<div className="edit-layer" role="dialog" aria-modal="true"><form className="edit-panel monthly-form meeting-form" onSubmit={async e=>{await saveMeeting(e);setAdminPanel(null)}}><button type="button" className="dialog-close" onClick={()=>setAdminPanel(null)} aria-label="Fechar">×</button><p className="eyebrow">PRÓXIMO ENCONTRO</p><h2>Dados do encontro</h2><label>Data e horário<input required type="datetime-local" value={meetingAt} onChange={e=>setMeetingAt(e.target.value)}/></label><label>Local<input value={meetingPlace} onChange={e=>setMeetingPlace(e.target.value)} placeholder="Ex.: Livraria, café ou chamada online"/></label><label>Observações<textarea value={meetingNotes} onChange={e=>setMeetingNotes(e.target.value)} placeholder="Ex.: levar uma frase favorita"/></label><div className="edit-actions"><button type="button" onClick={()=>setAdminPanel(null)}>Cancelar</button><button>Salvar encontro</button></div></form></div>}
    {adminPanel==='admins'&&<div className="edit-layer" role="dialog" aria-modal="true"><article className="edit-panel admin-card"><button className="dialog-close" onClick={()=>setAdminPanel(null)} aria-label="Fechar">×</button><p className="eyebrow">ADMINISTRAÇÃO</p><h2>Administradoras</h2><ul>{data.members.filter(member=>member.isAdmin).map(member=><li key={member.id}><strong>{member.name}</strong><span>{member.email}</span></li>)}</ul><form onSubmit={async e=>{await addAdmin(e);setAdminPanel(null)}}><label>Adicionar administradora<input required type="email" placeholder="E-mail de uma participante" value={adminEmail} onChange={e=>setAdminEmail(e.target.value)}/></label><button>Conceder acesso</button></form></article></div>}
    {adminPanel==='report'&&data.readingReport&&<div className="edit-layer" role="dialog" aria-modal="true"><article className="edit-panel admin-card report-card"><button className="dialog-close" onClick={()=>setAdminPanel(null)} aria-label="Fechar">×</button><p className="eyebrow">RELATÓRIO DO CLUBE</p><h2>Leituras das participantes</h2><ul>{data.readingReport.members.map(member=><li key={member.id}><strong>{member.name}</strong><span>{member.finished} lido(s) · {member.abandoned} abandonado(s)</span></li>)}</ul><h3>Quem leu cada livro</h3><ul>{data.readingReport.books.map(book=><li key={book.id}><strong>{book.title}</strong><span>{book.readers.join(', ')}</span></li>)}</ul></article></div>}
  </main>
}

function formatDateTime(date:string) { return new Date(date).toLocaleString('pt-BR',{dateStyle:'short',timeStyle:'short'}); }

function avatarSource(imageUrl?:string|null,userId?:string) { return imageUrl?.startsWith('r2:')?`/api/profile/photo?userId=${userId}`:imageUrl||''; }

function CommentHeader({user,date}:{user:{id:string;name:string;imageUrl?:string|null};date:string}) { const src=avatarSource(user.imageUrl,user.id); return <header className="comment-author">{src?<img src={src} alt={`Foto de ${user.name}`}/>:<span>{user.name[0]?.toUpperCase()}</span>}<div><strong>{user.name}</strong><small>{formatDateTime(date)}</small></div></header> }

function CommentList({comments,currentUserId,onUpdate,onDelete}:{comments:Comment[];currentUserId:string;onUpdate:(id:string,content:string)=>Promise<boolean>;onDelete:(id:string)=>Promise<boolean>}) { const [editingId,setEditingId]=useState<string|null>(null),[text,setText]=useState(''); return <div className="comment-list">{comments.length?comments.map(comment=>{const own=comment.user.id===currentUserId,editing=editingId===comment.id;return <article className="comment-item" key={comment.id}><CommentHeader user={comment.user} date={comment.createdAt}/>{editing?<><textarea className="comment-edit" maxLength={300} value={text} onChange={e=>setText(e.target.value)}/><div className="comment-controls"><small>{text.length}/300</small><button onClick={async()=>{if(await onUpdate(comment.id,text)){setEditingId(null);setText('')}}}>Salvar</button><button onClick={()=>setEditingId(null)}>Cancelar</button></div></>:<p>{comment.content}</p>}{own&&!editing&&<div className="comment-controls"><button onClick={()=>{setEditingId(comment.id);setText(comment.content)}}>Editar</button><button className="comment-delete" onClick={()=>void onDelete(comment.id)}>Excluir</button></div>}</article>}) :<p className="empty-comments">Ainda não há comentários para este livro.</p>}</div> }

function PublicProfile({member,books,onClose}:{member:Member;books:Book[];onClose:()=>void}) { const src=avatarSource(member.imageUrl,member.id); return <div className="edit-layer" role="dialog" aria-modal="true" aria-label={`Perfil de ${member.name}`}><article className="edit-panel public-profile"><button className="dialog-close" onClick={onClose} aria-label="Fechar">×</button><div className="public-profile-head">{src?<img src={src} alt={`Foto de ${member.name}`}/>:<span>{member.name[0]?.toUpperCase()}</span>}<div><p className="eyebrow">PARTICIPANTE DO CLUBE</p><h2>{member.name}</h2><p>{books.length} {books.length===1?'livro lido':'livros lidos'}</p></div></div><h3>Livros lidos</h3>{books.length?<ul className="public-books">{books.map(book=><li key={book.id}>{book.coverUrl?<img src={book.coverUrl} alt={`Capa de ${book.title}`}/>:<span>Sem capa</span>}<div><strong>{book.title}</strong><small>{book.author}</small></div></li>)}</ul>:<p className="empty-comments">Esta participante ainda não marcou nenhum livro como lido.</p>}</article></div> }

function BookForm({title,book,setBook,onSubmit,onClose}:{title:string;book:typeof emptyBook;setBook:(book:typeof emptyBook)=>void;onSubmit:(e:FormEvent)=>void;onClose:()=>void;isAdmin:boolean}) { return <div className="edit-layer" role="dialog" aria-modal="true"><form className="edit-panel" onSubmit={onSubmit}><button type="button" className="dialog-close" onClick={onClose} aria-label="Fechar">×</button><p className="eyebrow">LIVRO SUGERIDO</p><h2>{title}</h2><label>Título<input required value={book.title} onChange={e=>setBook({...book,title:e.target.value})}/></label><label>Autor(a)<input required value={book.author} onChange={e=>setBook({...book,author:e.target.value})}/></label><label>Sugerido por<input value={book.suggestedByLabel} onChange={e=>setBook({...book,suggestedByLabel:e.target.value})} placeholder="Seu nome"/></label><label>Gênero<input value={book.genre} onChange={e=>setBook({...book,genre:e.target.value})}/></label><label>URL da capa<input type="url" value={book.coverUrl} onChange={e=>setBook({...book,coverUrl:e.target.value})}/></label><label>Link de compra<input type="url" value={book.purchaseUrl} onChange={e=>setBook({...book,purchaseUrl:e.target.value})}/></label><label>Sinopse<textarea value={book.synopsis} onChange={e=>setBook({...book,synopsis:e.target.value})}/></label><div className="edit-actions"><button type="button" onClick={onClose}>Cancelar</button><button>Salvar sugestão</button></div></form></div> }

function EditForm({book,setBook,onSubmit,onClose}:{book:Book;setBook:(book:Book)=>void;onSubmit:(e:FormEvent)=>void;onClose:()=>void}) { return <div className="edit-layer" role="dialog" aria-modal="true"><form className="edit-panel" onSubmit={onSubmit}><button type="button" className="dialog-close" onClick={onClose} aria-label="Fechar">×</button><p className="eyebrow">EDITAR SUGESTÃO</p><h2>{book.title}</h2><p className="locked">O título permanece protegido.</p><label>Autor(a)<input value={book.author} onChange={e=>setBook({...book,author:e.target.value})}/></label><label>Sugerido por<input value={book.suggestedByLabel||''} onChange={e=>setBook({...book,suggestedByLabel:e.target.value})}/></label><label>Gênero<input value={book.genre||''} onChange={e=>setBook({...book,genre:e.target.value})}/></label><label>URL da capa<input value={book.coverUrl||''} onChange={e=>setBook({...book,coverUrl:e.target.value})}/></label><label>Link de compra<input value={book.purchaseUrl||''} onChange={e=>setBook({...book,purchaseUrl:e.target.value})}/></label><label>Sinopse<textarea value={book.synopsis||''} onChange={e=>setBook({...book,synopsis:e.target.value})}/></label><div className="edit-actions"><button type="button" onClick={onClose}>Cancelar</button><button>Salvar alterações</button></div></form></div> }

function ReadingCatalog({readings,ownStatuses,ownRatings,isAdmin,onEdit,onDelete,onStatus,onComments,onRate}:{readings:MonthlyReading[];ownStatuses:{bookId:string;state:ReadingStatus['state']}[];ownRatings:{bookId:string;score:number}[];isAdmin:boolean;onEdit:(reading:MonthlyReading)=>void;onDelete:(id:string)=>void;onStatus:(bookId:string,state:ReadingStatus['state'])=>void;onComments:(book:Book)=>void;onRate:(bookId:string,score:number)=>void}) { return <div className="reading-catalog">{readings.length?readings.flatMap(reading=>reading.books.map(({book})=>{const state=ownStatuses.find(status=>status.bookId===book.id)?.state||'NOT_STARTED',ownRating=ownRatings.find(rating=>rating.bookId===book.id)?.score||0,average=book.ratings.length?book.ratings.reduce((total,rating)=>total+rating.score,0)/book.ratings.length:0;return <article key={`${reading.id}-${book.id}`}><div className="catalog-cover">{book.coverUrl?<img src={book.coverUrl} alt={`Capa de ${book.title}`}/>:<span>Sem capa</span>}</div><p>{new Date(reading.month).toLocaleDateString('pt-BR',{month:'long',year:'numeric'})}</p><strong className="catalog-title">{book.title}</strong><p className="catalog-average">{book.ratings.length?`★ ${average.toFixed(1)} · ${book.ratings.length} ${book.ratings.length===1?'avaliação':'avaliações'}`:'Sem avaliações'}</p><div className="catalog-stars" aria-label="Sua avaliação">{[1,2,3,4,5].map(score=><button key={score} className={score<=ownRating?'selected':''} onClick={()=>onRate(book.id,score)} aria-label={`${score} estrelas`}>★</button>)}</div><div className="catalog-status"><button className={state==='FINISHED'?'active':''} onClick={()=>onStatus(book.id,'FINISHED')}>Li</button><button className={state==='ABANDONED'?'active abandoned':''} onClick={()=>onStatus(book.id,'ABANDONED')}>Abandonei</button></div><button className="catalog-comments" onClick={()=>onComments(book)}>Comentários</button>{isAdmin&&<div><button onClick={()=>onEdit(reading)}>Editar</button><button onClick={()=>onDelete(reading.id)}>Excluir</button></div>}</article>})):<p className="empty">Nenhuma leitura mensal definida ainda.</p>}</div> }

function BookCard({book,isAdmin,onDetails,onComments,onEdit,onContest,onDelete,onRead,onUpload}:{book:Book;isAdmin:boolean;onDetails:()=>void;onComments:()=>void;onEdit:()=>void;onContest:()=>void;onDelete:()=>void;onRead:()=>void;onUpload:(file?:File)=>void}) { const [open,setOpen]=useState(false); return <article className={`book-card ${book.isContested?'contested':''}`}><div className="book-cover">{book.coverUrl?<img src={book.coverUrl} alt={`Capa de ${book.title}`}/>:<span>Sem<br/>capa</span>}</div><div className="book-info"><p className="book-genre">{book.genre||'Gênero não informado'}</p><h3>{book.title}</h3><p className="book-author">{book.author}</p><p className="book-suggester">Sugerido por {book.suggestedByLabel||book.suggestedBy?.name||'participante do clube'}</p>{book.statuses?.length?<p className="book-suggester">Já lido por {book.statuses.map(s=>s.user.name).join(', ')}</p>:null}{book.isContested&&<p className="contested-label">Livro contestado{book.contestedBy?.name?` por ${book.contestedBy.name}`:''}.</p>}<div className="book-actions"><button className="add-book card-menu" onClick={()=>setOpen(!open)} aria-label="Ações do livro">+</button>{open&&<div className="book-menu"><button onClick={onDetails}>Mais informações</button><button onClick={onComments}>Comentários</button><button onClick={onRead}>Já li</button><button onClick={onEdit}>Editar</button>{!book.isContested&&<button className="danger" onClick={onContest}>Contestar</button>}<button className="danger" onClick={onDelete}>Excluir</button>{book.purchaseUrl&&<a href={book.purchaseUrl} target="_blank" rel="noreferrer">Comprar</a>}{book.epubKey&&<a href={`/api/books/${book.id}/epub`}>Baixar EPUB</a>}{isAdmin&&<label className="epub-upload">Enviar EPUB<input type="file" accept=".epub,application/epub+zip" onChange={e=>onUpload(e.target.files?.[0])}/></label>}</div>}</div></div></article> }
