'use client';

import { useEffect, useState } from 'react';
import Image from 'next/image';
import { authClient } from '../lib/auth-client';
import ClubDashboard from './club-dashboard';

export default function Home(){
  const s=authClient.useSession();
  const [register,setRegister]=useState(false),[forgot,setForgot]=useState(false),[resetToken,setResetToken]=useState(''),[name,setName]=useState(''),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[newPassword,setNewPassword]=useState(''),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
  useEffect(()=>{const params=new URLSearchParams(window.location.search);const token=params.get('token');if(token)setResetToken(token);if(params.get('error'))setError('Este link de recuperação não é mais válido. Solicite outro link.')},[]);
  const submit=async()=>{setBusy(true);setError('');try{const r=register?await authClient.signUp.email({email,password,name:name||email.split('@')[0]}):await authClient.signIn.email({email,password});if(r.error)setError(r.error.message||'Não foi possível continuar.')}catch{setError('Não foi possível concluir agora.')}finally{setBusy(false)}};
  const requestReset=async()=>{setBusy(true);setError('');setMessage('');try{const r=await authClient.requestPasswordReset({email,redirectTo:`${window.location.origin}/`});if(r.error)setError(r.error.message||'Não foi possível solicitar a recuperação.');else setMessage('Se este e-mail estiver cadastrado, enviaremos um link para redefinir a senha.')}catch{setError('Não foi possível solicitar a recuperação agora.')}finally{setBusy(false)}};
  const resetPassword=async()=>{setBusy(true);setError('');try{const r=await authClient.resetPassword({newPassword,token:resetToken});if(r.error)setError(r.error.message||'Não foi possível alterar a senha. Solicite um novo link.');else{setMessage('Senha atualizada. Agora você já pode entrar.');setResetToken('');setForgot(false);setNewPassword('');window.history.replaceState({},'',window.location.pathname)}}catch{setError('Não foi possível alterar a senha. Solicite um novo link.')}finally{setBusy(false)}};
  if(s.isPending)return <main className="center">Abrindo o clube…</main>;
  if(!s.data)return <main className="auth"><Image className="auth-logo auth-logo-horizontal" src="/logo-autentica-horizontal.png" width={403} height={91} alt="Autêntica Clube de Leitura" priority/><p>Um espaço para as nossas leituras e conversas.</p>{resetToken?<div className="form"><h2>Nova senha</h2><p>Escolha uma senha nova para acessar o clube.</p><input type="password" minLength={8} placeholder="Nova senha" value={newPassword} onChange={e=>setNewPassword(e.target.value)}/>{error&&<p className="error">{error}</p>}{message&&<p className="notice">{message}</p>}<button onClick={resetPassword} disabled={busy||newPassword.length<8}>{busy?'Aguarde…':'Salvar nova senha'}</button><button className="link" onClick={()=>{setResetToken('');window.history.replaceState({},'',window.location.pathname)}}>Voltar para entrar</button></div>:forgot?<div className="form"><h2>Recuperar senha</h2><p>Informe seu e-mail e enviaremos um link para criar uma nova senha.</p><input type="email" placeholder="E-mail" value={email} onChange={e=>setEmail(e.target.value)}/>{error&&<p className="error">{error}</p>}{message&&<p className="notice">{message}</p>}<button onClick={requestReset} disabled={busy||!email}>{busy?'Enviando…':'Enviar link de recuperação'}</button><button className="link" onClick={()=>{setForgot(false);setError('');setMessage('')}}>Voltar para entrar</button></div>:<div className="form">{register&&<input placeholder="Seu nome" value={name} onChange={e=>setName(e.target.value)}/>}<input type="email" placeholder="E-mail" value={email} onChange={e=>setEmail(e.target.value)}/><input type="password" placeholder="Senha" value={password} onChange={e=>setPassword(e.target.value)}/>{error&&<p className="error">{error}</p>}{message&&<p className="notice">{message}</p>}<button onClick={submit} disabled={busy}>{busy?'Aguarde…':register?'Criar perfil':'Entrar'}</button>{!register&&<button className="link" onClick={()=>{setForgot(true);setError('');setMessage('')}}>Esqueci minha senha</button>}<button className="link" onClick={()=>{setRegister(!register);setError('');setMessage('')}}>{register?'Já tenho perfil':'Cheguei pelo convite'}</button></div>}</main>;
  return <ClubDashboard userName={s.data.user.name||'Leitora'} onSignOut={()=>authClient.signOut()}/>;
}
